### ISSUE TITLE
Make AttestationServer URL Configurable

### ISSUE THREAD

**Issue by rhclayto** [GrapheneOS/Auditor#156] opened 2022-01-22 05:26 UTC
Currently the URL for the AttestationServer used by Auditor is hardcoded. https://github.com/GrapheneOS/AttestationServer/issues/140

This is a feature request to make the URL configurable, allowing on to run one's own AttestationServer & use it with the Auditor app that ships with GrapheneOS.

**Comment by brandsimon** [comment] 2022-01-31 16:08
This is a duplicate of #60

**Closed** 2022-01-31 21:07 UTC
